require("youal.set")
require("youal.plugins")
require("youal.map")
require("youal.sh")
require("youal.shebang")
-- require("youal.go")

-- require("youal.packer")
-- require("youal.ale")
-- require('hlargs').setup()
-- require('pqf').setup()
-- require"gitlinker".setup()
-- require("youal.autopairs")
-- require("youal.cmp")
-- require'colorizer'.setup()
-- require('nvim-ts-autotag').setup()
-- require("youal.color-picker")
