require("youal.set")
require("youal.plugins")
require("youal.map")

-- Has to be loaded before any other modules.
-- require('impatient')

-- require("youal.packer")
-- require("youal.ale")
-- require('hlargs').setup()
-- require("youal.neorg")
-- require('pqf').setup()
-- require"gitlinker".setup()
-- require("youal.autopairs")
-- require("youal.cmp")
-- require'colorizer'.setup()
-- require('nvim-ts-autotag').setup()
-- require("youal.color-picker")
-- require("youal.tagbar")
-- require("youal.tmux")
-- require("youal.sh")
-- require("youal.py")
